### PR TITLE
Revcheck ropensci/GSODR

### PR DESCRIPTION
**Pull request by adamhsparks**

### CODE REVIEW

**Comment by cderv** [comment]
Hi @adamhsparks ! 

Thanks for trying this experimental crandalf service built by @yihui ! 

@yihui I believe this will not work exactly as expected from what is described in the README. 
Github as a default policy to not run action from first time external contributor on a project. 
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
This mean opening the PR here will require a manual action from  us, at least the first time. 
It is possible that this can be configured differently (https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#configuring-required-approval-for-workflows-from-public-forks)

For the story, I believe this was made as protection against evil usage of public repository
https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/

@adamhsparks I can approve your workflow for this PR to work. 

In fact, there is no need to PR to this repo, everything can be done directly in your fork.
You just need to make the PR from your branch to your forked master branch. As actions seems to be activated on your fork, this should work as expected. This process is a bit described in the readme, bullet point 2. in https://github.com/yihui/crandalf#timeout

Hope it helps

**Comment by adamhsparks** [comment]
Thanks, I admit, I was puzzled by the directions to just follow the normal procedure for a pull request. I'd much rather run this as a part of my regular workflow for this repository.

**Comment by adamhsparks** [comment]
I'll work on my own fork, thanks for the tip, @cderv, and close this PR.

Many thanks for your patience and clarity in instructing me.

**Comment by yihui** [comment]
I've changed the permission setting to "Require approval for first-time contributors who are new to GitHub." Hopefully most future PRs won't need our approval any more. Thanks!

**Pull request closed without merging**
